(function () {
  'use strict';
  const tabs = [['SELF', '自分'], ['DELEGATED', '振る'], ['HOLD', '保留'], ['COMPLETED', '完了']]; let store; let state = 'SELF'; let todos = []; let readOnly = false; let token = new URLSearchParams(location.hash.slice(1)).get('token') || sessionStorage.getItem('management_ai_memo_token') || '';
  const $ = (id) => document.getElementById(id); const status = (text, error) => { $('status').textContent = text; $('status').className = error ? 'error' : ''; };
  function persistToken() { if (token) { sessionStorage.setItem('management_ai_memo_token', token); history.replaceState(null, '', location.pathname + location.search); } }
  function renderTabs() { $('tabs').replaceChildren(...tabs.map(([key, label]) => { const b = document.createElement('button'); b.textContent = label; b.className = key === state ? '' : 'secondary'; b.onclick = () => { state = key; render(); }; return b; })); }
  function render() { renderTabs(); const list = $('list'); list.replaceChildren(); todos.filter((todo) => todo.status === state).forEach((todo) => { const item = document.createElement('article'); item.className = 'todo'; const body = document.createElement('textarea'); body.value = todo.body; body.readOnly = readOnly; body.onchange = () => update(todo, { body: body.value }); const fields = document.createElement('div'); fields.className = 'fields'; [['source_person','誰から'],['target_person','誰に'],['delegated_to','委任先'],['due_date','期限'],['report_due_date','報告期限'],['report_content','報告内容']].forEach(([key, placeholder]) => { const input = document.createElement(key === 'report_content' ? 'textarea' : 'input'); input.placeholder = placeholder; input.value = todo[key] || ''; input.disabled = readOnly; input.onchange = () => update(todo, { [key]: input.value || null }); fields.appendChild(input); }); const select = document.createElement('select'); select.disabled = readOnly; tabs.forEach(([key, label]) => { const o = document.createElement('option'); o.value = key; o.textContent = label; o.selected = key === todo.status; select.appendChild(o); }); select.onchange = () => update(todo, { status: select.value, completed_at: select.value === 'COMPLETED' ? new Date().toISOString() : null }); const del = document.createElement('button'); del.textContent = '削除'; del.disabled = readOnly; del.onclick = () => { if (confirm('このTODOを削除しますか？')) update(todo, { is_deleted: true, deleted_at: new Date().toISOString() }); }; item.append(body, fields, select, del); list.appendChild(item); }); }
  async function update(todo, patch) { Object.assign(todo, patch); if (patch.is_deleted) todos = todos.filter((item) => item !== todo); try { await store.save(todo); render(); status('保存しました。'); } catch (error) { status('保存に失敗しました。入力値は保持されています。', true); } }
  async function register() { if (readOnly) return; const value = $('input').value; if (!value.trim()) return status('本文を入力してください。', true); try { const todo = todoService.createTodo({ body: value }); await store.save(todo); todos.push(todo); $('input').value = ''; await store.saveDraft(''); render(); status('そのまま登録しました。'); } catch (error) { status(error.message, true); } }
  async function organize() { if (!token) return status('AI整理には社内TOPから利用を開始してください。', true); const value = $('input').value; if (!value.trim()) return status('本文を入力してください。', true); $('ai').disabled = true; try { const response = await fetch(window.MANAGEMENT_AI_MEMO_CONFIG.apiUrl, { method: 'POST', headers: { 'Content-Type': 'text/plain;charset=UTF-8' }, body: JSON.stringify({ token, inputText: value, clientVersion: 'external-1', timezone: 'Asia/Tokyo' }) }); const result = await response.json(); if (!result.success) throw new Error(result.message || 'AI整理に失敗しました。'); const created = result.todos.map((todo) => todoService.createTodo({ body: todo.body, source_person: todo.sourcePerson, target_person: todo.targetPerson, due_date: todo.dueDate })); for (const todo of created) { await store.save(todo); todos.push(todo); } $('input').value = ''; await store.saveDraft(''); render(); status('AI整理して登録しました。'); } catch (error) { status(error.message || 'AI整理に失敗しました。入力と下書きを保持しています。', true); } finally { $('ai').disabled = false; } }
  function refreshSummary() { store.summary().then((value) => { $('summary').textContent = `保存件数: ${value.count}件 ／ 最終更新: ${value.lastUpdatedAt ? new Date(value.lastUpdatedAt).toLocaleString('ja-JP') : '未保存'}`; }).catch(() => { $('summary').textContent = '保存状態を取得できません。'; }); }
  function download(blob) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `management-ai-memo-${new Date().toISOString().slice(0, 10)}.maimemo`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 0); }
  async function exportBackup() { const pass = prompt('バックアップ用パスフレーズを入力してください。'); if (pass === null) return; try { download(await store.exportEncryptedBackup(pass)); status('暗号化バックアップを書き出しました。'); } catch (error) { status(error.message, true); } }
  async function importBackup(file) { if (!file) return; if (readOnly) return status('読取専用のため復元できません。', true); const pass = prompt('バックアップ作成時のパスフレーズを入力してください。'); if (pass === null) return; try { await store.importEncryptedBackup(file, pass); todos = await store.all(); const draft = await store.getDraft(); $('input').value = draft ? draft.text : ''; render(); refreshSummary(); status('バックアップを復元しました。'); } catch (error) { status(error.message, true); } }
  async function deleteAll() { if (readOnly) return status('読取専用のため全件削除できません。', true); if (prompt('確認のため「すべて削除」と入力してください。') !== 'すべて削除') return status('全件削除を中止しました。'); try { await store.deleteAllLocalData(); todos = []; $('input').value = ''; render(); refreshSummary(); status('端末内のデータをすべて削除しました。'); } catch (error) { status(error.message, true); } }
  function toggleSettings() { $('settings-panel').hidden = !$('settings-panel').hidden; if (!$('settings-panel').hidden) refreshSummary(); }
  (async () => { persistToken(); store = window.todoStore; const initialized = await store.init(); readOnly = initialized.readOnly; todos = await store.all(); const draft = await store.getDraft(); if (draft) $('input').value = draft.text; $('input').oninput = () => store.saveDraft($('input').value); $('save').onclick = register; $('ai').onclick = organize; $('settings').onclick = toggleSettings; $('backup-export').onclick = exportBackup; $('backup-import').onclick = () => $('backup-file').click(); $('backup-file').onchange = () => { importBackup($('backup-file').files[0]); $('backup-file').value = ''; }; $('delete-all').onclick = deleteAll; render(); })().catch((error) => status(error.message || '初期化に失敗しました。', true));
}());
